### Spring properties
# Service registers under this name
spring:
  application:
    name: paytm-accounts-microservice

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:9090/eureka/
        
server: 
  port: 9191

        
paytm.payment:
  sandbox:
    merchantId: FfgSFd16730854160250
    merchantKey: TFQG2CF2e0ZgwrhV
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Retail
    paytmUrl: https://securegw-stage.paytm.in/order/process
    callbackUrl: http://localhost:9191/pgresponse
    details:
      MID: ${paytm.payment.sandbox.merchantid}
      CHANNEL_ID: ${paytm.payment.sandbox.channelid}
      INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industrytypeid}
      WEBSITE: ${paytm.payment.sandbox.website}
      CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}